cc_test(
    name = "repository_test",
    srcs = ["repository_test.cpp"],
    data = ["@libgit2//:test_resources"],
    deps = [
        "//gitxx",
        "@catch2//:catch2_main",
        "@fmt",
    ],
)
